#
# https://hub.docker.com/r/inspircd/inspircd-docker/
#
version: '3.7'

services:

  ircd:
    image: inspircd/inspircd-docker
    container_name: ircd
    ports:
      - 6667:6667
      - 6697:6697
